//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCOemahJowo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mt_transaction
    {
        public int TRANS_ID { get; set; }
        public string DESCRIPTION { get; set; }
        public int PROD_ID { get; set; }
        public double PRICE { get; set; }
        public int CUST_ID { get; set; }
        public System.DateTime ENTRY_DATE { get; set; }
        public string ENTRY_USER { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public string UPDATE_USER { get; set; }
        public System.DateTime TRANS_DATE { get; set; }
        public int ITEM_AMT { get; set; }
        public string IS_GOJEK { get; set; }
        public System.Guid ssma_rowid { get; set; }
    
        public virtual mt_customer mt_customer { get; set; }
        public virtual mt_prod mt_prod { get; set; }
    }
}
