//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCOemahJowo.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class oemahjowodbEntities : DbContext
    {
        public oemahjowodbEntities()
            : base("name=oemahjowodbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<me_config> me_config { get; set; }
        public virtual DbSet<me_user> me_user { get; set; }
        public virtual DbSet<mt_customer> mt_customer { get; set; }
        public virtual DbSet<mt_prod> mt_prod { get; set; }
        public virtual DbSet<mt_transaction> mt_transaction { get; set; }
        public virtual DbSet<mt_transdet> mt_transdet { get; set; }
        public virtual DbSet<mt_prod_cat> mt_prod_cat { get; set; }
        public virtual DbSet<mt_trans_dtl> mt_trans_dtl { get; set; }
        public virtual DbSet<mt_trans_hdr> mt_trans_hdr { get; set; }
        public virtual DbSet<mg_shoplist> mg_shoplist { get; set; }
    }
}
